//
//  AccountConstant.swift
//  GoJekUser
//
//  Created by apple on 21/02/19.
//  Copyright © 2019 Appoets. All rights reserved.
//

import UIKit

//MARK:- String

enum AccountConstant {
        
    static let account = "My Account"
    static let language = "Language"
    static let resetPassword = "Reset Password"
    static let otpVerification = "OTP Verification"
    static let oldPassword = "Old Password"
    static let newPassword = "New Password"
    static let confirmPassword = "Confirm Password"
    static let otp = "OTP"
    static let invalidOtp = "Invalid OTP"
    static let enterOtp = "Enter OTP"
    static let logout = "Logout"
    static let logoutMsg = "Are you sure want to logout?"
    static let changePassword = "Change Password"
    static let promoCode = "Promo Codes"
    static let revenue = "Revenue"
    static let editTiming = "Edit Timing"
    static let editRestaurant = "Edit Restaurant"
    static let editShop = "Edit Shop"
    static let order = "Orders"
    static let totalEarning = "Total Earnings"
    static let todayRevenue = "Today Revenue"
    static let orderCancelled = "Order Cancelled"
    static let orderDelivered = "Order Delivered"
    static let monthlyEarning = "Monthly Earnings"
    static let openTime = "Open Time"
    static let closeTime = "Close Time"
    static let city = "City"
    static let Country = "Country"
    static let MaximumDeliveryTime = "Maximum Delivery Time"
    static let offerInPercentage = "Offer In Percentage"
    static let minAmt = "Min Amount"
    static let cuisine = "Cuisine"
    static let code = "Code"
    static let phoneNumber = "Phone Number"
    static let name = "Name"
    static let landMark = "Landmark"
    static let location = "Location"
    static let pureVegRestaurant = "Is this a pure veg restaurant ?"
    static let zipCode = "ZipCode"
    static let zone = "Zone"
    static let chooseCountry = "Choose Country"
    static let chooseCity  = "Choose City"
    static let search = "Search"
    static let countrySearchError = "No Country Found"
    static let citySearchError = "No City Found"
    static let countryCodeSearchError = "No Country Code Found"
    static let contactPerson = "Contact Person"
    static let selectCuisine = "Select Cuisine"
    static let commission = "Commission Percentage(%)"
    static let gstPercent = "Gst/Tax Percentage(%)"
    static let storePackageCharge = "Store Package Charge"
    static let storeResponseTime = "Shop Response Time (Secs)"
    static let flatNo = "Flat No."
    static let street = "Street"
    static let everyDay = "EveryDay"
    static let minimumAmt = "Minimum Amount"
    static let bestsellercount = "Best Seller Count"
    static let bestsellermonth = "Best Seller Timeline (In Month)"
    
    static let countryCodeEmpty = "Enter the country code"
    static let phoneEmpty = "Enter the phone number"
    static let emailEmpty = "Enter the email id"
    static let cityEmpty = "Enter the city"
    static let cuisineEmpty = "Enter the cuisine"
    static let statusEmpty = "Enter the status"
    static let minAmountEmpty = "Enter the minimum amount"
    static let offerPercentEmpty = "Enter the offer percent"
    static let maximumDeliveryTimeEmpty = "Enter the maximum delivery time"
    static let desEmpty = "Enter the description"
    static let landmarkEmpty = "Enter the landmark"
     static let locationEmpty = "Enter the location"
     static let shopresponseEmpty = "Enter the shop response time"
    static let countryEmpty = "Enter Country"
    static let commissionEmpty = "Enter Commission Percentage"
    static let monthError = "Enter valid month value"
    static let countError = "Enter valid count value"
    static let bestsellerError = "Enter the bestseller count"
    static let gstEmpty = "Enter Gst/Tax Percentage"
    static let zoneEmpty = "Enter the Zone"
    static let zipEmpty = "Enter the ZipCode"
    static let contactPersonEmpty = "Enter the Contact Person"
    static let enable = "Enable"
    static let disable = "Disable"
    static let nonVeg = "Non Veg"
    static let chartData = "You need to provide data for the chart."
    
    //Controller
    static let MyAccountController = "MyAccountController"
    static let ChangePasswordController = "ChangePasswordController"
    static let WebViewController = "WebViewController"
    static let AccountCollectionViewCell = "AccountCollectionViewCell"
    static let RevenueController = "RevenueController"
    static let PromoCodeListViewController = "PromoCodeListViewController"
    static let PromoViewController = "PromoViewController"

    static let EditRestaurantController = "EditRestaurantController"
    static let EditTimingController = "EditTimingController"
    static let TEditTimingTableViewCell = "EditTimingTableViewCell"
    static let TCuisineTableViewCell = "CuisineTableViewCell"
    static let TCuisineTableViewController = "CuisineTableViewController"
    static let CountryListCell = "CountryListCell"
    static let CountryCodeViewController = "CountryCodeViewController"
    
    //Images
    static let icprofile = "ic_profile"
    static let referFriend = "ic_gift_card"
    static let icprivacyPolicy = "ic_privacy_policy"
    static let icsupport = "ic_support"
    static let web = "ic_web"
    static let phone = "ic_phone"
    static let icmail = "ic_mail"
    static let languageImage = "ic_language"
    static let logoutImage = "ic_logout"
    static let ic_changePwd = "ic_changePwd"
    static let ic_revenue = "revenue"
    static let ic_promo = "ic_promo"
    static let edit = "edit"
    static let edit_Time = "edittime"
    
    //Parameter
    static let PCuisineId = "cuisine_id"
    static let PStoreName = "store_name"
    static let PStatus = "status"
    static let PIsVeg = "is_veg"
    static  let PEmail = "email"
    static let PEstimatedDeliveryTime = "estimated_delivery_time"
    static let PContactNumber = "contact_number"
    static let PPassword = "password"
    static let PStoreLocation = "store_location"
    static let PLatitude = "latitude"
    static let PLongitude = "longitude"
    static let PStoreZipcode = "store_zipcode"
    static let PContactPerson = "contact_person"
    static let PStorePackingCharges = "store_packing_charges"
    static let PZoneId = "zone_id"
    static let PStoreGst = "store_gst"
    static let POfferMinAmount = "offer_min_amount"
    static let POfferPercent = "offer_percent"
    static let PDescription = "description"
    static let PCountryId = "country_id"
    static let PCityId = "city_id"
    static let PCommission = "commission"
    static let PCountryCode = "country_code"
    static let PPicture = "picture"
    static let PMethod = "_method"
    static let PId = "id"
    static let PStoreTypeId = "store_type_id"
    static let PStoreResponseTime = "store_response_time"
    static let PFlat_no = "flat_no"
    static let PStreet = "street"
     static let Pfree_delivery = "free_delivery"
    static let Pfree_delivery_limit = "free_delivery_limit"
    static let Pbestseller_month = "bestseller_month"
    static let Pbestseller = "bestseller"
}

//MARK:- AccountAPI

enum AccountAPI {
    static let changePassword = "/shop/password"
    static let promocode = "/shop/promocode"
    static let logout = "/shop/logout"
    static let revenue = "/shop/total/storeorder"
    static let editTiming = "/shop/shopstiming"
    static let editRestaurant = "/shop/shops"
}

//MARK:- PickerType

enum PickerType: String {
    case countryCode = "CountryCode"
    case countryList = "CountryList"
    case stateList = "StateList"
    case cityList = "CityList"
}
